### ISSUE TITLE
Hi, do incoming calls work?

### ISSUE THREAD

**Issue by Hadenix** [SamarV-121/android_device_realme_mt6785-common#5]
I use imsinit but incoming calls do not work for me.

applied patches:
https://github.com/SamarV-121/android_vendor_extra/blob/lineage-18.1/patches/frameworks/opt/net/wifi/0001-wifi-Add-StaState-API.patch
https://github.com/SamarV-121/android_vendor_extra/blob/lineage-18.1/patches/frameworks/base/0008-WifiManager-Add-StaState-API.patch
https://github.com/SamarV-121/android_vendor_extra/blob/lineage-18.1/patches/frameworks/opt/net/ims/0001-Partially-Revert-Remove-references-to-deprecated-dev.patch

**Comment by Hadenix** [comment]
I will be grateful if you help. vendor from ROM android 9

**Comment by Hadenix** [comment]
build crdroid

**Comment by TheCloverly** [comment]
@Hadenix Sar crdroid already there sar

**Comment by TheCloverly** [comment]
@TheCloverly crdroid.net/RMX2001

**Comment by Iamlooker** [comment]
@devil-black-786 Lol

**Comment by Hadenix** [comment]
> tg

how to understand you

**Comment by devil-black-786** [comment]
@Hadenix send ur telegram group id wen

**Comment by Iamlooker** [comment]
@devil-black-786 Neber sur

**Comment by iamlordutkarsh** [comment]
@Iamlooker 😒

**Comment by iamlordutkarsh** [comment]
@iamlordutkarsh Tf

**Comment by Hadenix** [comment]
I wrote on the case and asked. I haven't seen a normal answer yet

**Comment by devil-black-786** [comment]
@Hadenix use patched libmtk for now

**Comment by kardebayan** [comment]
> I use imsinit but incoming calls do not work for me.
> 
> applied patches:
> https://github.com/SamarV-121/android_vendor_extra/blob/lineage-18.1/patches/frameworks/opt/net/wifi/0001-wifi-Add-StaState-API.patch
> https://github.com/SamarV-121/android_vendor_extra/blob/lineage-18.1/patches/frameworks/base/0008-WifiManager-Add-StaState-API.patch
> https://github.com/SamarV-121/android_vendor_extra/blob/lineage-18.1/patches/frameworks/opt/net/ims/0001-Partially-Revert-Remove-references-to-deprecated-dev.patch

this patches doesnt matters unless u use volte

**Comment by Hadenix** [comment]
> @Hadenix use patched libmtk for now

I did not see in the tree that it was used

**Comment by devil-black-786** [comment]
@Hadenix yup because oss ims works for them

**Comment by Hadenix** [comment]
> > I use imsinit but incoming calls do not work for me.
> > applied patches:
> > https://github.com/SamarV-121/android_vendor_extra/blob/lineage-18.1/patches/frameworks/opt/net/wifi/0001-wifi-Add-StaState-API.patch
> > https://github.com/SamarV-121/android_vendor_extra/blob/lineage-18.1/patches/frameworks/base/0008-WifiManager-Add-StaState-API.patch
> > https://github.com/SamarV-121/android_vendor_extra/blob/lineage-18.1/patches/frameworks/opt/net/ims/0001-Partially-Revert-Remove-references-to-deprecated-dev.patch
> 
> this patches doesnt matters unless u use volte

volte, I wanted to fix it too

**Comment by devil-black-786** [comment]
@Hadenix if oss ims not working then try using phh ims apk from CPH1859

**Comment by Hadenix** [comment]
> @Hadenix yup because oss ims works for them

you can link to see what and how? or talk to someone about this in the TG

**Comment by devil-black-786** [comment]
@Hadenix reference here 

https://github.com/CPH1859/proprietary_vendor_oppo_CPH1859/commit/c820a8bf12f5cab9a8573389b2b767e4992a23de

**Comment by devil-black-786** [comment]
@iamlordutkarsh mt6771 with prebuilt pie vendor 😂

**Comment by techyminati** [comment]
@devil-black-786 They use phh's ims with pie vendor ig

**Comment by Hadenix** [comment]
> > I use imsinit but incoming calls do not work for me.
> > applied patches:
> > https://github.com/SamarV-121/android_vendor_extra/blob/lineage-18.1/patches/frameworks/opt/net/wifi/0001-wifi-Add-StaState-API.patch
> > https://github.com/SamarV-121/android_vendor_extra/blob/lineage-18.1/patches/frameworks/base/0008-WifiManager-Add-StaState-API.patch
> > https://github.com/SamarV-121/android_vendor_extra/blob/lineage-18.1/patches/frameworks/opt/net/ims/0001-Partially-Revert-Remove-references-to-deprecated-dev.patch
> 
> Which chipset ?

mt6763 android 9 stock

**Comment by kardebayan** [comment]
> @devil-black-786 They use phh's ims with pie vendor ig

they use oss ims

**Comment by techyminati** [comment]
@kardebayan Who?

**Comment by kardebayan** [comment]
> @kardebayan Who?

@hadenix uses

**Comment by kardebayan** [comment]
@techyminati but for pie vendor oss ims will be dead anyways so use phh ims

**Comment by techyminati** [comment]
@kardebayan Agreeing

**Comment by devil-black-786** [comment]
@kardebayan full chatting  baji on GitHub

**Comment by kardebayan** [comment]
@devil-black-786 yes github bess for chating

**Comment by techyminati** [comment]
@kardebayan Now stop lmao that guy was just asking for incoming calls issue

**Comment by Hadenix** [comment]
> @Hadenix reference here
> 
> [CPH1859/proprietary_vendor_oppo_CPH1859@c820a8b](https://github.com/CPH1859/proprietary_vendor_oppo_CPH1859/commit/c820a8bf12f5cab9a8573389b2b767e4992a23de)

if you use it? ImsInit then delete or what?

**Comment by SamarV-121** [comment]
Tf is going on ;_____;

First of all, this is a wrong place to ask that

**Comment by sarthakroy2002** [comment]
@SamarV-121
